### ISSUE TITLE
[공용 다이얼로그] 텍스트에 따른 다이얼로그 크기 조절

### ISSUE THREAD

**Issue by hr955** [JangHyeLyn/Exchange-Diary-Android#33]
내용
====
contentText 항목 미사용시 텍스트 뷰의 위치 및 다이얼로그 크기 조절 필요

**Comment by AnKyungMoo** [comment]
ContentText 항목을 사용하고 Title을 사용하지 않는 것으로 결정
대신 ContentText의 Text Size를 변경할 수 있도록 기능 추가
